Qubes: mpf, watch-vms
mpf
===
- only for powering off

watch-vms
=========
- don't wrap long lines
- highlight sys-firewall
- don't pring priv-curr

diff --git a/qubes/mpf b/qubes/mpf
--- a/qubes/mpf
+++ b/qubes/mpf
@@ -14,12 +14,14 @@ then
     fi
 fi
 
+if [[ "$1" == "-n" || "$2" == "-n" ]]
+then
+    echo "This option has been deprecated. Aborting."
+    exit 1
+fi
+
 echo "Powering down VMs"
 
 qvm-shutdown --wait --all
 
-if [[ "$1" != "-n" && "$2" != "-n" ]]
-then
-    echo "Halting system"
-    systemctl poweroff
-fi
+systemctl poweroff
